Mention improved data validation error messages in 5.0 migration guide
cakephp/docs pull request #7686
Opened 2023-08-28 11:37 UTC by Murl080

Refers to: https://github.com/cakephp/cakephp/pull/17189

2023-08-28 11:57 UTC, ravage84 requested changes

2023-08-28 11:57 UTC, ravage84 commented on en/appendices/5-0-migration-guide.rst
> +  For example, ``The provided value must be greater than or equal to `5```.
```suggestion
  For example, ``The provided value must be greater than or equal to \`5\``.
```

2023-08-28 17:00 UTC, ravage84 approved these changes

2023-08-29 00:49 UTC, Arhell approved these changes

2023-08-29 15:27 UTC, markstory commented on en/appendices/5-0-migration-guide.rst
> +  For example, ``The provided value must be greater than or equal to \`5\``.
```suggestion
  For example, ``The provided value must be greater than or equal to \`5\```.
```

2023-08-29 15:27 UTC, merged